### ISSUE TITLE
when i enter the game its closed suddenly after map loaded

### ISSUE THREAD

**Issue by noping5811** [vetid/otc#4]
I use extreme last version injector after csgo last update its size about 18 Mb after I have this problem .Thank you for helping

**Comment by idk583** [comment]
same.

**Comment by jxian725** [comment]
> I use extreme last version injector after csgo last update its size about 18 Mb after I have this problem .Thank you for helping



> same.


The DLL is clearly outdated as for the latest csgo update. However you can still make it works by fixing the memory address to match the newest csgo update.

**Comment by noping5811** [comment]
> > I use extreme last version injector after csgo last update its size about 18 Mb after I have this problem .Thank you for helping
> 
> > same.
> 
> The DLL is clearly outdated as for the latest csgo update. However you can still make it works by fixing the memory address to match the newest csgo update.

Thank you for answering but I am not familiar with this coding things :=)

**Comment by vetid** [comment]
run this program to fix crashes:
https://github.com/vetid/otcfix
